#ifndef MLIB_HPP
#define MLIB_HPP

#include"all_of.hpp"
#include"amount.hpp"
#include"constexpr_for.hpp"
#include"constexpr_while.hpp"
#include"constructable_with.hpp"
#include"factorial.hpp"
#include"fibonacci.hpp"
#include"find.hpp"
#include"fixed_string.hpp"
#include"for_each.hpp"
#include"get.hpp"
#include"index_sequence.hpp"
#include"loop.hpp"
#include"meta_struct.hpp"
#include"one_of.hpp"
#include"on_all.hpp"
#include"Print.hpp"
#include"refl_get.hpp"
#include"select.hpp"
#include"traits.hpp"
#include"transform.hpp"
#include"tuple.hpp"
#include"tuple_inheritance.hpp"
#include"tuple_reverse.hpp"
#include"type.hpp"

#endif